# Generated by Django 5.1.6 on 2025-11-10 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authcart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='host',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='teammessage',
            name='session',
        ),
        migrations.RemoveField(
            model_name='teammessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
        migrations.DeleteModel(
            name='GreenMission',
        ),
        migrations.DeleteModel(
            name='GameSession',
        ),
        migrations.DeleteModel(
            name='TeamMessage',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
